/**
 * Schema loading utilities for schema-aware GROQ linting.
 *
 * Uses @sanity/codegen's readSchema to load schema.json files
 * generated by `sanity schema extract`.
 */

import { readSchema } from '@sanity/codegen'
import type { SchemaType } from 'groq-js'
import { existsSync } from 'node:fs'
import { resolve } from 'node:path'

/**
 * Load a schema from a JSON file path.
 *
 * @param path - Path to schema.json file
 * @returns The parsed schema
 * @throws If the file doesn't exist or is invalid
 */
export async function loadSchema(path: string): Promise<SchemaType> {
  return readSchema(path)
}

/**
 * Common locations to look for schema.json files
 */
const SCHEMA_CANDIDATES = [
  'schema.json',
  'sanity.schema.json',
  '.sanity/schema.json',
  'studio/schema.json',
]

/**
 * Auto-discover a schema.json file in a project directory.
 *
 * Looks in common locations for schema files generated by
 * `sanity schema extract`.
 *
 * @param root - Project root directory (defaults to cwd)
 * @returns Path to schema file, or null if not found
 */
export function findSchemaPath(root: string = process.cwd()): string | null {
  for (const candidate of SCHEMA_CANDIDATES) {
    const fullPath = resolve(root, candidate)
    if (existsSync(fullPath)) {
      return fullPath
    }
  }
  return null
}

/**
 * Try to load a schema from common locations.
 *
 * @param root - Project root directory (defaults to cwd)
 * @returns The schema if found, or null
 */
export async function tryLoadSchema(root: string = process.cwd()): Promise<SchemaType | null> {
  const schemaPath = findSchemaPath(root)
  if (!schemaPath) {
    return null
  }

  try {
    return await loadSchema(schemaPath)
  } catch {
    return null
  }
}

/**
 * Get document type names from a schema.
 *
 * @param schema - The schema to extract document types from
 * @returns Array of document type names
 */
export function getDocumentTypes(schema: SchemaType): string[] {
  return schema
    .filter((item): item is Extract<typeof item, { type: 'document' }> => item.type === 'document')
    .map((doc) => doc.name)
}

/**
 * Get a document definition by name from a schema.
 *
 * @param schema - The schema to search
 * @param typeName - The document type name (e.g., 'post')
 * @returns The document definition, or undefined
 */
export function getDocumentByType(
  schema: SchemaType,
  typeName: string
): Extract<SchemaType[number], { type: 'document' }> | undefined {
  return schema.find(
    (item): item is Extract<typeof item, { type: 'document' }> =>
      item.type === 'document' && item.name === typeName
  )
}

/**
 * Get field names for a document type.
 *
 * @param schema - The schema to search
 * @param typeName - The document type name
 * @returns Array of field names, or empty array if type not found
 */
export function getFieldsForType(schema: SchemaType, typeName: string): string[] {
  const doc = getDocumentByType(schema, typeName)
  if (!doc) {
    return []
  }
  return Object.keys(doc.attributes)
}
